using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Linq.Mapping;

namespace PingORM.Configuration
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public class ColumnAttribute : DataAttribute
    {
        public bool IsPrimaryKey { get; set; }
        public bool IsPartitionKey { get; set; }
        public bool IsAutoGenerated { get; set; }
        public string Expression { get; set; }
        public bool IsNestedType { get; set; }
    }
}
